# Generated by Django 6.0.3 on 2026-03-20 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('icon', models.CharField(default='bi-book', max_length=50, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '知识分类',
                'verbose_name_plural': '知识分类',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
                ('image', models.ImageField(blank=True, upload_to='knowledge/', verbose_name='封面')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='knowledge.knowledgecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '知识文章',
                'verbose_name_plural': '知识文章',
                'ordering': ['-created_at'],
            },
        ),
    ]
