# Generated by Django 6.0.3 on 2026-03-20 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宠物名')),
                ('breed', models.CharField(max_length=50, verbose_name='品种')),
                ('age', models.CharField(blank=True, max_length=20, verbose_name='年龄')),
                ('gender', models.CharField(blank=True, choices=[('male', '公'), ('female', '母')], max_length=6, verbose_name='性别')),
                ('photo', models.ImageField(blank=True, upload_to='pets/', verbose_name='照片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '宠物档案',
                'verbose_name_plural': '宠物档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccine', '疫苗'), ('checkup', '体检')], max_length=10, verbose_name='类型')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('date', models.DateField(verbose_name='日期')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='下次日期')),
                ('hospital', models.CharField(blank=True, max_length=200, verbose_name='医院')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_reminded', models.BooleanField(default=False, verbose_name='已提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'ordering': ['-date'],
            },
        ),
    ]
