# Generated by Django 6.0.3 on 2026-03-21 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='会话标识')),
                ('role', models.CharField(choices=[('user', '用户'), ('bot', '机器人'), ('agent', '人工客服')], max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, verbose_name='会话标识')),
                ('status', models.CharField(choices=[('pending', '等待接入'), ('active', '咨询中'), ('closed', '已结束')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_requests', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '人工咨询',
                'verbose_name_plural': '人工咨询',
                'ordering': ['-created_at'],
            },
        ),
    ]
