# Generated by Django 6.0.3 on 2026-03-20 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('icon', models.CharField(default='bi-heart', max_length=50, verbose_name='图标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '服务类别',
                'verbose_name_plural': '服务类别',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('duration', models.IntegerField(default=60, verbose_name='服务时长(分钟)')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='封面图片')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='服务地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('avg_rating', models.FloatField(default=0, verbose_name='平均评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评价数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '服务项目',
                'verbose_name_plural': '服务项目',
                'ordering': ['-created_at'],
            },
        ),
    ]
