# Generated by Django 6.0.3 on 2026-03-21 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='status',
            field=models.CharField(choices=[('lost', '走失中'), ('found', '已找到'), ('adopted', '已领养'), ('expired', '已失效')], default='lost', max_length=10, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='SavedLost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lost_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='community.lostpet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '走失信息收藏',
                'verbose_name_plural': '走失信息收藏',
                'unique_together': {('lost_pet', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '帖子收藏',
                'verbose_name_plural': '帖子收藏',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
