# Generated by Django 6.0.4 on 2026-04-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_lostpet_status_savedlost_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
    ]
